"use client";
import React, { useEffect } from "react";
import "./Supercharge.css";
import AOS from "aos";
import "aos/dist/aos.css";
const Supercharge = () => {
  useEffect(() => {
    AOS.init({
      duration: 800,
      once: false,
    });
  }, []);

  return (
    <div className="mt-20 md:mx-36  px-6">
      
        <div className="mt-8" data-aos="fade-up">
          
          <div className="grid md:grid-cols-2 gap-8">
            <div className="box_small bg-[#0F0F0F] rounded-2xl p-6">
              <img className="w-10" src="/dh1.svg" />
              <h3 className="text-lg mt-3  text-white">
                20% Profit sharing
              </h3>
              <p className="mt-2">
              20% of the total profits generated by CopyWing will be distributed among CWN token holders as dividends.
              </p>
            </div>
            <div className="box_small bg-[#0F0F0F] rounded-2xl p-6">
              <img className="w-10" src="/dh2.svg" />
              <h3 className="text-lg mt-3  text-white">Dividends</h3>
              <p className="mt-2">
              CWN token holders are entitled to receive dividends from the contract pool, which is funded by profits generated through our copy trading activities.
              </p>
            </div>
            <div className="box_small bg-[#0F0F0F] rounded-2xl p-6">
              <img className="w-10" src="/dh3.svg" />
              <h3 className="text-lg mt-3  text-white">Incentivized Holdings</h3>
              <p className="mt-2">
              To encourage long-term holding, dividends are distributed periodically, creating a strong incentive for users to retain their CWN tokens. 
              </p>
            </div>
            <div className="box_small bg-[#0F0F0F] rounded-2xl p-6">
              <img className="w-10" src="/dh4.svg" />
              <h3 className="text-lg mt-3  text-white">Exclusive Benifits</h3>
              <p className="mt-2">
              Holding CWN tokens may grant you access to special features, reduced trading fees, and priority access to new tools and updates.
              </p>
            </div>
          </div>
        </div>
      </div>
    
  );
};

export default Supercharge;
